/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
 * Generated on: 24-Feb-2020 02:20:26
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 251
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s16,15 -> [-1 1)
 *   Product         : s40,31 -> [-256 256)
 *   Accumulator     : s40,31 -> [-256 256)
 *   Round Mode      : convergent
 *   Overflow Mode   : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019b\extern\include\tmwtypes.h 
 */
const int BL = 251;
const int16_T B[251] = {
        7,      7,      7,      7,      7,      7,      8,      8,      8,
        8,      9,      9,     10,     10,     10,     11,     12,     12,
       13,     13,     14,     15,     16,     16,     17,     18,     19,
       20,     21,     22,     23,     24,     25,     26,     28,     29,
       30,     31,     33,     34,     36,     37,     39,     40,     42,
       43,     45,     47,     48,     50,     52,     53,     55,     57,
       59,     61,     63,     64,     66,     68,     70,     72,     74,
       76,     78,     80,     82,     84,     86,     88,     90,     92,
       94,     96,     98,    100,    102,    104,    106,    108,    110,
      112,    114,    116,    118,    120,    122,    123,    125,    127,
      129,    130,    132,    134,    135,    137,    138,    140,    141,
      143,    144,    145,    147,    148,    149,    150,    151,    152,
      153,    154,    155,    156,    157,    157,    158,    159,    159,
      160,    160,    161,    161,    161,    161,    162,    162,    162,
      162,    162,    161,    161,    161,    161,    160,    160,    159,
      159,    158,    157,    157,    156,    155,    154,    153,    152,
      151,    150,    149,    148,    147,    145,    144,    143,    141,
      140,    138,    137,    135,    134,    132,    130,    129,    127,
      125,    123,    122,    120,    118,    116,    114,    112,    110,
      108,    106,    104,    102,    100,     98,     96,     94,     92,
       90,     88,     86,     84,     82,     80,     78,     76,     74,
       72,     70,     68,     66,     64,     63,     61,     59,     57,
       55,     53,     52,     50,     48,     47,     45,     43,     42,
       40,     39,     37,     36,     34,     33,     31,     30,     29,
       28,     26,     25,     24,     23,     22,     21,     20,     19,
       18,     17,     16,     16,     15,     14,     13,     13,     12,
       12,     11,     10,     10,     10,      9,      9,      8,      8,
        8,      8,      7,      7,      7,      7,      7,      7
};
