/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
 * Generated on: 24-Feb-2020 02:20:26
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 251
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s16,15 -> [-1 1)
 *   Product         : s40,31 -> [-256 256)
 *   Accumulator     : s40,31 -> [-256 256)
 *   Round Mode      : convergent
 *   Overflow Mode   : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include <dsp.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019b\extern\include\tmwtypes.h 
 */

#define NUM_BANDS 7
#define NUM_COEFFS 251

 // Band 1
extern const int BL1;
extern const fractional B1[NUM_COEFFS];

// Band 2
extern const int BL2;
extern const fractional B2[NUM_COEFFS];

// Band 3
extern const int BL3;
extern const fractional B3[NUM_COEFFS];

// Band 4
extern const int BL4;
extern const fractional B4[NUM_COEFFS];

// Band 5
extern const int BL5;
extern const fractional B5[NUM_COEFFS];

// Band 6
extern const int BL6;
extern const fractional B6[NUM_COEFFS];

// Band 7
extern const int BL7;
extern const fractional B7[NUM_COEFFS];

extern const fractional* BANDS[];

